forge 'https://forgeapi.puppetlabs.com'

mod 'stahnma/epel'
mod 'puppetlabs/stdlib'
mod 'crayfishx/firewalld'

mod 'ebrc/ebrc_yum_repo',
  :git => 'https://github.com/EuPathDB/puppet-ebrc_yum_repo.git'

mod 'ebrc/globus_connect_server',
  :git => 'https://github.com/EuPathDB/puppet-globus_connect_server.git'

mod 'local/profiles',
  :path => './src/profiles'
  :latest

mod 'local/roles',
  :path => './src/roles'
  :latest
